# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fb9f299edb2dc1e77015ea66131b6683aab222902497be1c2e2f65e338663df55e7f23deeb1180788fbda392f81cd5f5c5f5ce14bb741e1ddecfede0de600aaa

test:
  secret_key_base: 703466c6b0d21d10144e60d513f204f09be9be9941fb86533ce183464dea1ad84b23711f399eb8d42e5b442e08f23a187088c507ee2c1e6dc2bf30ef9fb237ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
